version: "3.5"

services:

    git-db:
      image: postgres:12-alpine
      container_name: git-db
      hostname: git-db
      restart: always
      environment:
        - POSTGRES_DB=${GOGS_POSTGRESQL_DATABASE}
        - POSTGRES_USER=${GOGS_POSTGRESQL_USER}
        - POSTGRES_PASSWORD=${GOGS_POSTGRESQL_PASSWORD}
      ports:
        - ${GOGS_POSTGRESQL_PORT_BINDING}:5432
      networks:
        - git-network
      volumes:
        - git-db-data:/var/lib/postgresql/data

    git:
      image: gogs/gogs:0.11.91
      container_name: git
      hostname: git
      restart: always
      environment:
        - RUN_CROND=true
      volumes:
        - git-data:/data
      networks:
        - git-network
        - proxy-network
      ports:
        - ${GOGS_SSH_PORT_BINDING}:22
        - ${GOGS_HTTP_PORT_BINDING}:3000
      depends_on:
        - git-db
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy-network"
        - "traefik.http.routers.git.service=git"
        - "traefik.http.routers.git.rule=Host(`git.${YOUR_DOMAIN}`)"
        - "traefik.http.routers.git.entrypoints=websecure"
        - "traefik.http.routers.git.tls.certresolver=proxyresolver"
        - "traefik.http.services.git.loadbalancer.server.port=3000"


networks:

    git-network:
      name: git-network
      driver: bridge

    proxy-network:
      external: true


volumes:

    git-data:
      driver_opts:
        type: none
        device: ${GOGS_DATA}
        o: bind

    git-db-data:
      driver_opts:
        type: none
        device: ${GOGS_POSTGRESQL_DATA}
        o: bind