version: "3.5"


services:

  registry:
    image: registry
    container_name: registry
    hostname: registry
    ports:
      - ${REGISTRY_PORT}:5000
    volumes:
      - registry-data:/var/lib/registry
      - registry-config-file/etc/docker/registry/config.yml
      - registry-password-file:/etc/docker/registry/htpasswd
    networks:
      - registry-network

  registry-ui:
    image: joxit/docker-registry-ui:static
    container_name: registry-ui
    ports:
      -  ${REGISTRY_UI_PORT}:80
    environment:
      - REGISTRY_URL=http://registry:5000
      - RELETE_IMAGES=true
      - REGISTRY_TITLE=Docker Registry
    networks:
      - registry-network
    depends_on:
      - registry

networks:

  registry-network:
    name: registry-network
    driver: bridge

volumes:

    registry-data:
      driver_opts:
        type: none
        device: ${REGISTRY_DATA}
        o: bind

    registry-config-file:
      driver_opts:
        type: none
        device: ${REGISTRY_CONFIG_FILE}
        o: bind

    registry-password-file:
      driver_opts:
        type: none
        device: ${REGISTRY_PASSWORD_FILE}
        o: bind