version: "3.5"


services:

  registry:
    image: registry
    container_name: registry
    hostname: registry
    restart: always
    ports:
      - ${REGISTRY_PORT}:5000
    volumes:
      - registry-data:/var/lib/registry
      - registry-config:/etc/docker/registry
    networks:
      - proxy-network
      - registry-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-network"
      - "traefik.http.routers.registry.service=registry"
      - "traefik.http.routers.registry.rule=Host(`registry.${YOUR_DOMAIN}`)"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.tls.certresolver=myresolver"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"

  registry-ui:
    image: joxit/docker-registry-ui:static
    container_name: registry-ui
    restart: always
    ports:
      -  ${REGISTRY_UI_PORT}:80
    environment:
      - REGISTRY_URL=http://registry:5000
      - PULL_URL=$PULL_URL
      - DELETE_IMAGES=true
      - REGISTRY_TITLE=Docker Registry
    networks:
      - proxy-network
      - registry-network
    depends_on:
      - registry
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-network"
      - "traefik.http.routers.registry-ui.service=registry-ui"
      - "traefik.http.routers.registry-ui.rule=Host(`registryui.${YOUR_DOMAIN}`)"
      - "traefik.http.routers.registry-ui.entrypoints=websecure"
      - "traefik.http.routers.registry-ui.tls.certresolver=myresolver"
      - "traefik.http.services.registry-ui.loadbalancer.server.port=80"

networks:

   proxy-network:
      external: true

   registry-network:
      name: registry-network
      driver: bridge

volumes:

    registry-data:
      driver_opts:
        type: none
        device: ${REGISTRY_DATA}
        o: bind

    registry-config:
      driver_opts:
        type: none
        device: ${REGISTRY_CONFIG}
        o: bind
