version: "3.5"


services:

    registry-db:
      image: postgres:latest
      container_name: registry-db
      hostname: registry-db
      restart: always
      volumes:
        - proget-postgresql-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=${PROGET_POSTGRESQL_DATABASE}
        - POSTGRES_USER=${PROGET_POSTGRESQL_USER}
        - POSTGRES_PASSWORD=${PROGET_POSTGRESQL_PASSWORD}
      ports:
        - ${PROGET_POSTGRES_PORT}:5432
      networks: 
        - registry-network

    registry:
      image: inedo/proget:latest
      container_name: registry
      hostname: registry
      restart: always
      environment:
        - PROGET_DATABASE=Host=registry-db; Database=${PROGET_POSTGRESQL_DATABASE}; Username=${PROGET_POSTGRESQL_USER}; Password=${PROGET_POSTGRESQL_PASSWORD};
      volumes:
        - proget-registry:/var/proget/registry
        - proget-extensions:/var/proget/extensions
      ports:
        - ${PROGET_HTTP_PORT}:80
      networks:
        - registry-network
      depends_on:
        - registry-db


networks:
  registry-network:
    name: registry-network
    driver: bridge


volumes:

    proget-registry:
      driver_opts:
        type: none
        device: ${PROGET_PACKAGES}
        o: bind

    proget-extensions:
      driver_opts:
        type: none
        device: ${PROGET_EXTENSIONS}
        o: bind

    proget-postgresql-data:
      driver_opts:
        type: none
        device: ${PROGET_POSTGRESQL_DATA}
        o: bind